---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https-rook
      protocol: HTTPS
      port: 443
      hostname: "rook.kharnox.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-secret-rook
    - name: https-prometheus
      protocol: HTTPS
      port: 443
      hostname: "prometheus.kharnox.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-secret-prometheus
      allowedRoutes:
        namespaces:
          from: All
    - name: https-alertmanager
      protocol: HTTPS
      port: 443
      hostname: "alertmanager.kharnox.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-secret-alertmanager
