---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.5.1@sha256:d4e60a414117c5b9c949f8fc84cd516f07c24415dfcfd85645a3c220d0dafbec
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
