---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.1@sha256:3fa56edb8ff4f6c397bb5c6ad66265542f28dbfc89d78fb48f4902b39471e8c2
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
