---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie-db
  namespace: mealie
spec:
  chart:
    spec:
      chart: cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 1m0s
