---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  chart:
    spec:
      chart: mealie
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mealie
        namespace: flux-system
  interval: 1m0s
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              # -- image tag
              # @default -- chart.appVersion
              tag: '2.1.0'
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Brussels
    ingress:
      main:
        enabled: false
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main:
            main:
            - path: /app/data/
              readOnly: false
