---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sources
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/workload/sources
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/workload/core
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cluster-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/workload/apps
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cluster-core
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
  timeout: 5m
  wait: false
