---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.9.3@sha256:3191141730b5062769f806ea6130c30709b19c8289e77e49c5d28061bbad6e7a
            env:
              TZ: Europe/Brussels
              HASS_SERVER: http://localhost:8123
              HASS_HTTP_X_FORWARDED_FOR: true
              HASS_HTTP_TRUSTED_PROXY_1: 10.244.0.48
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            # envFrom:
            #   - secretRef:
            #       name: "ha-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.104.1@sha256:66b4f0e6d32da53b0cf6af7cb0894b4078a93f2e160a9270c539e12e1ebf278d
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /config/.code-server
              - --extensions-dir
              - /config/.code-server
              - --port
              - "12321"
              - /config
            env:
              HASS_SERVER: http://localhost:8123
              # HASS_TOKEN:
              #   secretKeyRef:
              #     name: home-assistant-secret
              #     key: vscode_hass_token
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8123
        annotations:
          lbipam.cilium.io/ips: 192.168.129.175
      code-server:
        ports:
          code-server:
            port: 12321
    route:
      app:
        hostnames:
          - "ha.kharnox.com"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-ha
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /code/
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /
            backendRefs:
              - identifier: code-server
                port: 12321
          - backendRefs:
              - identifier: app
                port: 8123
    persistence:
      config:
        existingClaim: "ha"
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: "home-assistant-cache"
        globalMounts:
          - path: /config/.venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
