---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-donetick
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5@sha256:b14301dd53d8b26ff8843bf406c69334bf97bcf11406da35cc598a40b1a20db5
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: donetick
      owner: donetick
      secret:
        name: database-donetick
