---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: donetick
  namespace: donetick
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      donetick:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: donetick/donetick
              tag: v0.1.60@sha256:849a43d9e363a858e0bc325f6dcd9fa7432082a0a7e080411cc5588533284cea
            env:
              - name: DT_ENV
                value: selfhosted
              - name: DT_DATABASE_HOST
                value: db-donetick-rw
              - name: DT_DATABASE_PORT
                value: 5432
              - name: DT_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: database-donetick
                    key: username
              - name: DT_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: database-donetick
                    key: password
              - name: DT_DATABASE_NAME
                value: donetick
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/ping
                    port: &port 2021
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: donetick
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["dt.kharnox.com"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-donetick
    persistence:
      config:
        type: configMap
        name: donetick-config
        globalMounts:
          - path: "/config/selfhosted.yaml"
            subPath: selfhosted.yaml
            readOnly: true
      data:
        existingClaim: donetick-data
        globalMounts:
          - path: /donetick-data
