---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: observability
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.87.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    fullnameOverride: vm
    victoria-metrics-operator:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      # Enable deployment validation webhook
      validation:
        enabled: true
    grafana:
      enabled: true
